### ISSUE TITLE
Multiple database bugs

### ISSUE THREAD

**Issue by xhatt** [h0rn3t/fastapi-async-sqlalchemy#17]
When I was using a multi database connection, the following error occurred. After troubleshooting, I found that the reason should be that I called in model.pycreate_middleware_and_session_proxy like this
```python
from fastapi_async_sqlalchemy.middleware import create_middleware_and_session_proxy

SQLAlchemyMiddleware, database = create_middleware_and_session_proxy()
```
Then when the middleware is used, it should be with the database variable I just created, but in the source code, it is with the db of the global variable in the module, which leads to a bug.
The specific error is in line 55 of `middleware.py`, where a global variable was mistakenly used and its second return value should be used. Because I did not initialize SQLAlchemyMiddleware for the module's global variables, I created `SQLAlchemyMiddleware` myself. So the global variable db in the module has not been initialized.

```python
Traceback (most recent call last):
  File "/Users/xhz/PycharmProjects/venv/fastapi_demo/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xhz/PycharmProjects/venv/fastapi_demo/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xhz/PycharmProjects/venv/fastapi_demo/lib/python3.11/site-packages/fastapi/applications.py", line 284, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/xhz/PycharmProjects/venv/fastapi_demo/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/xhz/PycharmProjects/venv/fastapi_demo/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/xhz/PycharmProjects/venv/fastapi_demo/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/xhz/PycharmProjects/venv/fastapi_demo/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/Users/xhz/PycharmProjects/venv/fastapi_demo/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xhz/PycharmProjects/venv/fastapi_demo/lib/python3.11/site-packages/fastapi_async_sqlalchemy/middleware.py", line 55, in dispatch
    async with db(commit_on_exit=self.commit_on_exit):
  File "/Users/xhz/PycharmProjects/venv/fastapi_demo/lib/python3.11/site-packages/fastapi_async_sqlalchemy/middleware.py", line 79, in __aenter__
    raise SessionNotInitialisedError
fastapi_async_sqlalchemy.exceptions.SessionNotInitialisedError: 
        Session not initialised! Ensure that DBSessionMiddleware has been initialised before
        attempting database access.
        
```

Modify the dispatch function of `middleware.py`
Before modification:
```python
        async def dispatch(self, request: Request, call_next: RequestResponseEndpoint):
            async with db(commit_on_exit=self.commit_on_exit):
                return await call_next(request)
```
After modification:
```python
        async def dispatch(self, request: Request, call_next: RequestResponseEndpoint):
            async with DBSession(commit_on_exit=self.commit_on_exit):
                return await call_next(request)
```
So he can use his own internal variables

**Comment by h0rn3t** [comment]
need  more code to understand

**Comment by h0rn3t** [comment]
@xhatt try
